"""
SIGNAL_RULES — keyword-classifier catalog for the Signal Radar.

Each rule converts a news article into a typed signal task.
Confidence tiers:
  85-95 — unambiguous regulatory phrases (low false-positive risk)
  65-80 — clear context, mild keyword collision risk
  40-60 — broad keywords (RM must verify before outreach)

regulation tag values: "DPDP", "RBI", "ONDC", "DGCA", "KGW", "GST", "MeitY", ""
domain values: "liability" | "cyber_financial" | "property_engineering"
             | "employee_benefits" | "transit_motor" | "generic"
"""

# ── Legacy generic-business rules (preserved verbatim from original SIGNAL_RULES) ─
_LEGACY_RULES = [
    {
        "id": "funding_round", "label": "Funding round", "regulation": "", "domain": "generic",
        "why": "Board, investor, governance risk rises", "angle": "D&O, Key Person, Cyber",
        "keywords": ["funding", "fundraise", "raised", "raises", "series a", "series b", "series c", "seed round", "investment", "valuation"],
        "priority": 1, "confidence": 60, "stage": "Series A",
        "profile": {"has_investors": "Yes", "data_sensitivity": "High"},
    },
    {
        "id": "warehouse_factory", "label": "Warehouse / factory", "regulation": "", "domain": "generic",
        "why": "Physical asset exposure rises", "angle": "Property, IAR, Fire, CGL",
        "keywords": ["warehouse", "factory", "manufacturing", "plant", "facility", "fulfilment", "fulfillment", "dark-store", "dark store", "deployment", "deployments"],
        "priority": 4, "confidence": 55,
        "profile": {"operations": "Hybrid", "physical_assets": ["Manufacturing plant / factory", "Warehouse / fulfilment centre"], "hardware_software_split": 0.7},
    },
    {
        "id": "drone_robotics", "label": "Drone / robotics expansion", "regulation": "DGCA", "domain": "generic",
        "why": "Regulatory and third-party liability", "angle": "Drone RPAS, IAR",
        "keywords": ["drone", "uav", "robotics", "autonomous", "dgca", "defence", "defense", "counter-uas", "counter unmanned", "drone park"],
        "priority": 6, "confidence": 65, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Lab / R&D equipment", "Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"], "hardware_software_split": 0.55},
    },
    {
        "id": "fintech_rbi", "label": "Fintech licence / RBI mention", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Regulated data and operational risk", "angle": "Cyber, PI, D&O, Crime",
        "keywords": ["rbi", "nbfc", "payment aggregator", "fintech", "lending licence", "lending license", "lending business", "licence", "license", "sebi", "irdai"],
        "priority": 5, "confidence": 70, "sector": "Fintech",
        "profile": {"data_sensitivity": "High", "data_handled": ["Payments / financial transactions", "Personal identity data (KYC / Aadhaar)"], "regulatory": ["RBI / SEBI / IRDAI licensed", "DPDP Act obligations"], "payment_or_card_program": True},
    },
    {
        "id": "healthcare_expansion", "label": "Healthcare expansion", "regulation": "", "domain": "generic",
        "why": "Patient data and professional liability", "angle": "Cyber, PI, CGL",
        "keywords": ["healthcare", "hospital", "clinic", "patient", "diagnostic", "doctor", "medical", "pharma", "gmv", "ai-driven healthcare"],
        "priority": 4, "confidence": 60, "sector": "Healthtech",
        "profile": {"data_sensitivity": "High", "data_handled": ["Health / medical data", "Personal identity data (KYC / Aadhaar)"], "healthcare_operations": True},
    },
    {
        "id": "hiring_spike", "label": "Hiring spike", "regulation": "", "domain": "generic",
        "why": "Employee exposure grows", "angle": "WC, Group Health, EPLI",
        "keywords": ["hiring", "hire", "headcount", "employees", "workforce", "layoff", "layoffs", "restructuring", "campus"],
        "priority": 4, "confidence": 50,
        "profile": {"team_size": 120},
    },
    {
        "id": "export_import", "label": "Export / import news", "regulation": "", "domain": "generic",
        "why": "Transit and credit exposure appears", "angle": "Marine Cargo, Trade Credit",
        "keywords": ["export", "exports", "import", "imports", "global market", "international markets", "overseas", "shipment", "supply chain"],
        "priority": 4, "confidence": 55,
        "profile": {"export_us_pct": 20.0, "physical_assets": ["Warehouse / fulfilment centre"]},
    },
    {
        "id": "product_recall", "label": "Product recall / safety issue", "regulation": "", "domain": "generic",
        "why": "Liability exposure becomes immediate", "angle": "Product Liability, CGL",
        "keywords": ["recall", "defect", "safety issue", "fire incident", "battery fire", "contamination", "failure", "product-performance"],
        "priority": 6, "confidence": 65,
        "profile": {"product_recall_exposure": True},
    },
    {
        "id": "ipo_preipo", "label": "IPO / pre-IPO news", "regulation": "", "domain": "generic",
        "why": "Director liability and scrutiny rise", "angle": "D&O, Crime, Cyber",
        "keywords": ["ipo", "pre-ipo", "pre ipo", "listing", "listed", "sebi filing", "drhp", "public issue", "confidential ipo", "pre-filing"],
        "priority": 7, "confidence": 70, "stage": "Series B+",
        "profile": {"has_investors": "Yes", "funding_stage": "Series B+"},
    },
]

# ── Liability domain (signals.md lines 61-85) ────────────────────────────────────
_LIABILITY_RULES = [
    {
        "id": "ondc_odr_arbitration_surge", "label": "ONDC ODR arbitration surge", "regulation": "ONDC", "domain": "liability",
        "why": "Breakdown in Level 1 grievance redressal; breaching 30-day Consumer Protection mandate triggers fines and class actions",
        "angle": "Professional Indemnity / Tech E&O, Public Liability, I-select Liability",
        "keywords": ["odr arbitration", "ondc grievance", "dispute resolution officer", "consumer protection 30-day"],
        "priority": 7, "confidence": 85,
        "profile": {"regulatory": ["IT Act / CERT-In obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "rbi_loan_matching_deprecation", "label": "Loan-matching algorithm deprecation", "regulation": "RBI", "domain": "liability",
        "why": "Reactive compliance with RBI Nov 2025 multi-lender impartiality rules indicates prior algorithmic bias and D&O exposure",
        "angle": "D&O, Financial Services PI, Corporate Cover II",
        "keywords": ["loan matching algorithm", "multi-lender impartiality", "rbi digital lending directions", "lender matching deprecated"],
        "priority": 8, "confidence": 88, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed", "DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "dark_pattern_ui_overhaul", "label": "Dark-pattern UI overhaul", "regulation": "RBI", "domain": "liability",
        "why": "Removal of countdown timers and default opt-ins implies historical deceptive practices and unresolved consumer complaints",
        "angle": "Tech E&O, D&O, Enterprise Secure Package Policy",
        "keywords": ["dark patterns", "countdown timer removed", "default opt-in", "checkout flow overhaul"],
        "priority": 6, "confidence": 70,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "idrc_escalation_surge", "label": "IDRC escalation surge", "regulation": "KGW", "domain": "liability",
        "why": "High IDRC review volume under Karnataka Gig Worker Bill signals platform-worker friction and EPL exposure",
        "angle": "Employment Practices Liability, Employers Compensation, Business Shield SME",
        "keywords": ["internal dispute resolution committee", "idrc escalation", "gig worker grievance", "karnataka gig worker"],
        "priority": 7, "confidence": 85,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "ondc_reputation_ledger_drop", "label": "ONDC reputation ledger drop", "regulation": "ONDC", "domain": "liability",
        "why": "Drop in seller-app reputation score implies fulfilment failures and product quality degradation; leading indicator of recall/liability claims",
        "angle": "Product Liability, Public Liability, Merchants Cover III",
        "keywords": ["ondc reputation ledger", "seller app reputation", "ondc score drop", "network participant rating"],
        "priority": 8, "confidence": 90,
        "profile": {"data_sensitivity": "High", "product_recall_exposure": True},
    },
    {
        "id": "rbi_apr_disclosure_rollout", "label": "Dynamic APR disclosure rollout", "regulation": "RBI", "domain": "liability",
        "why": "Late implementation of matched/unmatched loan offer and APR disclosures violates RBI multi-lender rules",
        "angle": "Financial Services PI, D&O, Business Shield SME",
        "keywords": ["annual percentage rate disclosure", "matched loan offer", "unmatched offer", "apr disclosure dla"],
        "priority": 7, "confidence": 82, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "payment_or_card_program": True},
    },
    {
        "id": "lsp_cash_recovery_complaints", "label": "Unrecorded cash recovery complaints", "regulation": "RBI", "domain": "liability",
        "why": "RBI mandates same-day recording of physical cash recoveries; complaints signal rogue recovery agents and RE liability",
        "angle": "Crime / Fidelity, Financial Services PI, D&O",
        "keywords": ["cash recovery complaint", "recovery agent harassment", "lsp cash recovery", "same-day cash recording"],
        "priority": 7, "confidence": 80,
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "dro_turnover_spike", "label": "Dispute Resolution Officer turnover", "regulation": "ONDC", "domain": "liability",
        "why": "Rapid DRO turnover for ONDC mediation implies unmanageable edge-case dispute volume and governance toxicity",
        "angle": "Tech E&O, D&O, Employment Practices Liability",
        "keywords": ["dispute resolution officer", "dro turnover", "ondc mediation", "grievance officer change"],
        "priority": 6, "confidence": 70,
        "profile": {"regulatory": ["IT Act / CERT-In obligations"]},
    },
    {
        "id": "kgw_radius_veto", "label": "Welfare Board algorithm veto", "regulation": "KGW", "domain": "liability",
        "why": "Karnataka Welfare Board public veto on radius reductions >20% signals acute platform safety violation",
        "angle": "Employers Compensation, Public Liability, CGL / I-Elite",
        "keywords": ["welfare board veto", "algorithmic veto", "throttling radius reduction", "karnataka platform safety"],
        "priority": 8, "confidence": 88,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.5},
    },
    {
        "id": "rbi_kfs_tenor_mismatch", "label": "KFS sanctioned-tenor mismatch", "regulation": "RBI", "domain": "liability",
        "why": "Failure to align Key Facts Statement with final API outputs violates RBI multi-lender disclosure mandates",
        "angle": "Tech E&O, Financial Services PI, Enterprise Secure Package",
        "keywords": ["key facts statement", "sanctioned tenor", "kfs mismatch", "loan tenor discrepancy"],
        "priority": 7, "confidence": 80, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "ondc_odr_optout_surge", "label": "ONDC ODR opt-out surge", "regulation": "ONDC", "domain": "liability",
        "why": "Network participants opting out of ODR face suspension, implying severe impending revenue loss",
        "angle": "Business Interruption, D&O, Corporate Cover II",
        "keywords": ["odr opt-out", "ondc network suspension", "secondary network participant", "ondr withdrawal"],
        "priority": 6, "confidence": 78,
        "profile": {"data_sensitivity": "High"},
    },
    {
        "id": "rbi_cims_reporting_delay", "label": "RBI CIMS DLA reporting delay", "regulation": "RBI", "domain": "liability",
        "why": "Failure by Chief Compliance Officer to certify DLA compliance by deadline triggers massive statutory liability",
        "angle": "D&O, Cyber, Financial Services PI",
        "keywords": ["cims portal", "centralised information management system", "dla compliance certification", "rbi mismatch notice"],
        "priority": 8, "confidence": 88, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "cert_in_poc_designated": True},
    },
    {
        "id": "app_store_recovery_complaints", "label": "App-store recovery-agent complaints", "regulation": "RBI", "domain": "liability",
        "why": "Rating drops correlated with 'recovery agent' keyword density signal LSP aggressive tactics and absolute RE liability",
        "angle": "Public Liability, Crime / Fidelity, I-select Liability",
        "keywords": ["recovery agent complaints", "app store rating drop", "lsp harassment", "aggressive collection"],
        "priority": 6, "confidence": 60,
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "api_access_revoked_aggregator", "label": "Aggregator API access revoked", "regulation": "RBI", "domain": "liability",
        "why": "Termination of API access suggests fair-practices code non-compliance and imminent LSP-RE litigation",
        "angle": "Tech E&O, CGL / I-Elite, MSME Suraksha Kavach",
        "keywords": ["api access revoked", "aggregator terminated", "developer portal revocation", "fair practices code"],
        "priority": 6, "confidence": 65,
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "rbi_tos_post_deadline_patch", "label": "Post-deadline ToS patching", "regulation": "RBI", "domain": "liability",
        "why": "Reactive legal patching after RBI multi-lender rules enforcement indicates flawed prior due diligence",
        "angle": "D&O, Professional Indemnity / Tech E&O",
        "keywords": ["terms of service update", "wayback machine legal", "post-deadline tos", "reactive legal patch"],
        "priority": 5, "confidence": 55,
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "ondc_binding_arbitration_clause", "label": "ODR binding arbitration clause", "regulation": "ONDC", "domain": "liability",
        "why": "Preemptive legal shielding by ONDC sellers anticipating high dispute volume signals high-risk product portfolio",
        "angle": "CGL / I-Elite, Product Liability",
        "keywords": ["binding arbitration", "odr arbitration clause", "ondc seller terms", "consumer arbitration agreement"],
        "priority": 5, "confidence": 65,
        "profile": {"product_recall_exposure": True},
    },
    {
        "id": "rbi_impartiality_doc_revisions", "label": "Loan-matching impartiality revisions", "regulation": "RBI", "domain": "liability",
        "why": "Frequent erratic updates to documented matching methodology suggest repeated regulatory stress test failures",
        "angle": "Financial Services PI, Tech E&O, Business Shield SME",
        "keywords": ["impartiality metric", "loan matching documentation", "rbi stress test", "matching methodology revision"],
        "priority": 6, "confidence": 72, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "rbi_lsp_fee_flow_shift", "label": "LSP fee-collection flow shift", "regulation": "RBI", "domain": "liability",
        "why": "RBI mandates REs pay LSPs directly; abrupt fee-flow changes indicate prior non-compliance and impending fines",
        "angle": "Crime / Fidelity, Financial Services PI",
        "keywords": ["lsp fee collection", "borrower deduction", "fintech payment flow shift", "lsp direct payment"],
        "priority": 6, "confidence": 75, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "fintech_nbfc_disclosure_revision", "label": "NBFC partnership disclosure revision", "regulation": "RBI", "domain": "liability",
        "why": "Sudden shifts in third-party risk disclosure indicate underlying NBFC-fintech partnership instability",
        "angle": "D&O, Trade Credit, Corporate Cover II",
        "keywords": ["nbfc partnership disclosure", "third-party risk disclosure", "partnership revenue exposure", "quarterly partnership revision"],
        "priority": 6, "confidence": 65, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "rbi_endorsement_disclaimer_appearance", "label": "RBI-endorsement disclaimer appearance", "regulation": "RBI", "domain": "liability",
        "why": "Corrective action against misusing CIMS reporting to imply RBI backing violates 2025 guidelines",
        "angle": "Public Liability, Tech E&O",
        "keywords": ["rbi endorsement disclaimer", "rbi backed dla", "lending app disclaimer", "rbi disclosure correction"],
        "priority": 5, "confidence": 70, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "ondc_network_investigation", "label": "ONDC edge-case network investigation", "regulation": "ONDC", "domain": "liability",
        "why": "ONDC taking over dispute investigation implies Buyer/Seller App failure of 48-hour response and 30-day resolution SLA",
        "angle": "Professional Indemnity / Tech E&O",
        "keywords": ["ondc edge-case investigation", "ondc network investigation", "48-hour sla", "buyer app response failure"],
        "priority": 6, "confidence": 78,
        "profile": {"data_sensitivity": "High"},
    },
    {
        "id": "dla_delisting_notice", "label": "DLA delisting by RE", "regulation": "RBI", "domain": "liability",
        "why": "REs severing LSP ties due to technical or statutory due-diligence failure signals extreme operational disruption",
        "angle": "D&O, Business Interruption, Business Edge Policy",
        "keywords": ["dla delisting", "digital lending app removed", "re terminates lsp", "rbi due diligence failure"],
        "priority": 7, "confidence": 80, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "penalty_calc_module_change", "label": "Penal charge module change", "regulation": "RBI", "domain": "liability",
        "why": "Adjustments to penal charge calculations react to RBI disclosure audits",
        "angle": "Financial Services PI, I-select Liability",
        "keywords": ["penalty charge calculation", "penal charge module", "matched loan view", "rbi disclosure audit"],
        "priority": 5, "confidence": 65, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "kgw_conciliation_officer_spike", "label": "Conciliation officer hiring spike", "regulation": "KGW", "domain": "liability",
        "why": "Platforms staffing rapidly for Karnataka Gig Worker Act dispute mandates and 90-day Labour Tribunal adjudication",
        "angle": "Employment Practices Liability, CGL / I-Elite",
        "keywords": ["conciliation officer", "labour tribunal", "karnataka gig adjudication", "90-day dispute"],
        "priority": 6, "confidence": 78,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "kgw_algorithmic_disclosure_update", "label": "Algorithmic monitoring disclosure update", "regulation": "KGW", "domain": "liability",
        "why": "Aggregators updating worker-app algorithmic decision disclosures under 2025 Karnataka transparency mandates",
        "angle": "Tech E&O, Employers Compensation, Group Safeguard",
        "keywords": ["algorithmic monitoring disclosure", "gig worker app transparency", "karnataka ordinance disclosure", "automated monitoring apk"],
        "priority": 6, "confidence": 75,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
]

# ── Cyber & Financial Lines (signals.md lines 97-127) ────────────────────────────
_CYBER_FINANCIAL_RULES = [
    {
        "id": "dpdp_consent_manager_hiring", "label": "Consent Manager specialist hiring", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Reactive hiring ahead of Nov 2026 Consent Manager deadline indicates Phase II readiness gap",
        "angle": "Cyber, D&O, Business Shield SME",
        "keywords": ["consent manager integration", "consent manager specialist", "dpdp phase ii hiring", "consent framework engineer"],
        "priority": 7, "confidence": 82,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "rbi_24h_db_sync_latency", "label": "Foreign-server sync latency >20h", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Approaching the 24-hour foreign-server deletion threshold; breach triggers immediate RBI censure",
        "angle": "Cyber, Financial Services PI, Enterprise Secure Package",
        "keywords": ["24-hour data deletion", "foreign server latency", "data localisation deadline", "cross-border lending data"],
        "priority": 9, "confidence": 92, "sector": "Fintech",
        "profile": {"data_localisation_status": "Overseas", "regulatory": ["RBI / SEBI / IRDAI licensed", "DPDP Act obligations"]},
    },
    {
        "id": "dpdp_age_gate_aadhaar_integration", "label": "Aadhaar / DigiLocker age-gate", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Age-gating tools indicate processing of children's data requiring verifiable parental consent to avoid ₹200 cr penalty",
        "angle": "Cyber, D&O, Tech E&O",
        "keywords": ["aadhaar age gate", "digilocker integration", "verifiable parental consent", "minors data processing"],
        "priority": 8, "confidence": 85,
        "profile": {"data_handled": ["Minors' / children's data", "Personal identity data (KYC / Aadhaar)"], "regulatory": ["DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "dpdp_sdf_dpo_publication", "label": "DPO contact published", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPO publication signals SDF threshold crossed, activating DPIA and audit obligations",
        "angle": "Cyber, D&O, Crime / Fidelity, IAR Policy",
        "keywords": ["data protection officer", "dpo published", "significant data fiduciary", "sdf designation"],
        "priority": 8, "confidence": 90,
        "profile": {"sdf_probability": 0.85, "regulatory": ["DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "dpdp_dpia_vendor_rush", "label": "DPIA vendor procurement rush", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Rushed mandatory annual Data Protection Impact Assessments correlate with missed vulnerabilities",
        "angle": "Cyber, Professional Indemnity / Tech E&O",
        "keywords": ["dpia vendor", "data protection impact assessment", "dpia procurement", "annual dpia"],
        "priority": 6, "confidence": 75,
        "profile": {"sdf_probability": 0.7, "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_legitimate_use_deprecation", "label": "'Legitimate use' clause deprecation", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Forced shift from GDPR-style lawful bases to DPDP consent-driven architecture; legacy retention risk",
        "angle": "Cyber, D&O, CGL / I-Elite",
        "keywords": ["legitimate use deprecated", "privacy policy update dpdp", "consent driven architecture", "lawful basis removed"],
        "priority": 6, "confidence": 78,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_algorithmic_fairness_module", "label": "Algorithmic fairness module deployment", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "SDFs deploying mandated fairness assessments; failure invites discrimination lawsuits and DPB intervention",
        "angle": "Tech E&O, Cyber, Employment Practices Liability",
        "keywords": ["algorithmic fairness assessment", "fairness module", "sdf fairness audit", "ai bias assessment"],
        "priority": 7, "confidence": 80,
        "profile": {"ai_in_product": True, "sdf_probability": 0.7, "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_itemized_consent_rollout", "label": "Itemized consent notice rollout", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPDP multi-lingual itemized consent notices; clunky rollout threatens data monetisation",
        "angle": "Cyber, Business Interruption, Corporate Cover II",
        "keywords": ["itemized consent notice", "multi-lingual consent", "eighth schedule consent", "dpdp consent ui"],
        "priority": 5, "confidence": 72,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_3year_deletion_logic", "label": "3-year inactivity deletion logic", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "E-commerce/social media fiduciaries implementing mandatory 3-year inactive-user deletion; bugs cause illegal retention",
        "angle": "Cyber, D&O, Corporate Cover II",
        "keywords": ["3-year deletion", "inactive user purge", "dpdp retention trigger", "data deletion logic"],
        "priority": 6, "confidence": 78,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpb_complaint_api_endpoint", "label": "DPB complaint API endpoint", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Direct conduits to Data Protection Board grievance portal; high traffic signals mass privacy complaints",
        "angle": "Cyber, D&O, Public Liability",
        "keywords": ["dpb complaint api", "data protection board portal", "dpdp grievance endpoint", "digital grievance portal"],
        "priority": 7, "confidence": 85,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "rbi_dynamic_auth_sdk_deployment", "label": "Dynamic authentication SDK deployment", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Rushing RBI Apr 2026 dynamic-auth deadline for non-card-present transactions; integration failure halts processing",
        "angle": "Cyber, Financial Services PI, Crime / Fidelity",
        "keywords": ["dynamic authentication sdk", "non-card-present 2fa", "rbi authentication directions", "multi-factor authentication deadline"],
        "priority": 7, "confidence": 80, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "payment_or_card_program": True},
    },
    {
        "id": "dpdp_minor_ad_tracking_removal", "label": "Minor ad-tracking cookie removal", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Mitigating prohibited targeted advertising to children under DPDP Act",
        "angle": "Cyber, D&O, Tech E&O",
        "keywords": ["ad tracking removed", "minor targeted advertising", "child ad cookie", "dpdp ad ban"],
        "priority": 6, "confidence": 70,
        "profile": {"data_handled": ["Minors' / children's data"], "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_repermission_campaign", "label": "Legacy re-permissioning campaign", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Re-consent campaigns for pre-DPDP data; low opt-in threatens enterprise valuation",
        "angle": "D&O, Business Interruption",
        "keywords": ["re-permissioning campaign", "re-consent notice", "pre-dpdp data", "consent refresh email"],
        "priority": 5, "confidence": 65,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_right_to_nominate", "label": "Right-to-nominate interface flow", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPDP nomination of heirs for data rights presents complex data lifecycle management risks",
        "angle": "Cyber, Tech E&O",
        "keywords": ["right to nominate", "data heir nomination", "dpdp nomination interface", "incapacity data nominee"],
        "priority": 4, "confidence": 70,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_data_mapping_legacy", "label": "Legacy data mapping integration", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Late data mapping signals severe blind spots in cross-border flows; KPMG flagged as primary transition risk",
        "angle": "Cyber, Business Shield SME",
        "keywords": ["data mapping tool", "legacy system mapping", "cross-border data flow", "dpdp data inventory"],
        "priority": 5, "confidence": 60,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_localisation_status": "Unknown"},
    },
    {
        "id": "dpdp_outsourcing_exemption", "label": "Outsourcing exemption restructuring", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "BPOs restructuring for foreign-data exemption; misclassification leads to dual-jurisdiction penalties",
        "angle": "D&O, Professional Indemnity",
        "keywords": ["outsourcing exemption", "bpo restructuring dpdp", "foreign data exemption", "dpdp bpo carveout"],
        "priority": 5, "confidence": 68,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_employee_data_silo", "label": "Employee data silo separation", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPDP limits use of employee data for unrelated commercial purposes without explicit secondary consent",
        "angle": "Employment Practices Liability, Cyber",
        "keywords": ["employee data silo", "hr data segregation", "secondary consent employee", "dpdp hr compliance"],
        "priority": 5, "confidence": 65,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_72h_breach_search_spike", "label": "72-hour breach legal-search spike", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Enterprises seeking rapid counsel signal latent breach attempting to avoid ₹200 cr non-notification penalty",
        "angle": "Cyber, Crime / Fidelity, D&O",
        "keywords": ["72-hour breach", "personal data breach notification", "dpb notification", "data breach legal counsel"],
        "priority": 9, "confidence": 88,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_sensitivity": "High"},
    },
    {
        "id": "dpdp_consent_withdrawal_fix", "label": "Consent-withdrawal dark pattern fix", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Fixing asymmetric consent withdrawal — focus of DPB Phase I enforcement",
        "angle": "Cyber, Tech E&O",
        "keywords": ["consent withdrawal dark pattern", "asymmetric consent", "dpb dark pattern", "withdrawal flow fix"],
        "priority": 5, "confidence": 70,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_iso27001_retention_revision", "label": "ISO 27001 retention schedule revision", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Aligning retention with DPDP purpose-specific timelines; legacy unstructured data becomes toxic liability",
        "angle": "Cyber, D&O",
        "keywords": ["iso 27001 retention", "purpose specific timeline", "data retention schedule", "dpdp retention policy"],
        "priority": 4, "confidence": 60,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "rbi_tokenization_deployment", "label": "Non-card-present tokenization deployment", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Direct compliance with RBI 2025 authentication directions; integration failure disrupts cash flow",
        "angle": "Financial Services PI, Business Interruption, Enterprise Secure Package",
        "keywords": ["dynamic tokenization", "non-card-present", "payment gateway tokenization", "rbi auth directions"],
        "priority": 7, "confidence": 78, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "payment_or_card_program": True},
    },
    {
        "id": "dpdp_dpo_reporting_line_change", "label": "DPO board-reporting line change", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Elevating DPO to direct board reporting addresses DPDP accountability scrutiny",
        "angle": "D&O, Employment Practices Liability",
        "keywords": ["dpo reporting line", "ciso board reporting", "data protection officer escalation", "dpdp accountability"],
        "priority": 5, "confidence": 70,
        "profile": {"regulatory": ["DPDP Act obligations"], "sdf_probability": 0.7},
    },
    {
        "id": "rbi_sandbox_attestation_failure", "label": "Sandbox attestation submission failure", "regulation": "RBI", "domain": "cyber_financial",
        "why": "NBFCs failing functional compliance demonstration before Jun 30 2026 deadline",
        "angle": "D&O, Financial Services PI",
        "keywords": ["sandbox attestation", "regulatory sandbox failure", "digital lending registration", "rbi sandbox"],
        "priority": 7, "confidence": 82, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "fintech_bank_mca_restructure", "label": "Fintech-Bank MCA liability restructure", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Explicit liability reallocation reduces partnership viability and creates revenue volatility",
        "angle": "D&O, Trade Credit, Enterprise Secure Package",
        "keywords": ["fintech bank liability", "mca filing restructure", "partnership liability allocation", "rbi partnership update"],
        "priority": 6, "confidence": 65, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "dpdp_90day_grievance_tracker", "label": "90-day grievance tracker installation", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPDP 90-day grievance resolution mandate; overflows trigger DPB audits",
        "angle": "Cyber, Tech E&O",
        "keywords": ["90-day grievance", "dpdp grievance metric", "customer support api header", "data grievance tracker"],
        "priority": 4, "confidence": 65,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_restricted_transfer_disclosure", "label": "Restricted-territory transfer disclosure", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Central Government restricted-country notification forces costly foreign infra decoupling",
        "angle": "Cyber, D&O",
        "keywords": ["restricted territory transfer", "cross-border restriction", "dpdp transfer notification", "foreign server decoupling"],
        "priority": 6, "confidence": 72,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_localisation_status": "Restricted"},
    },
    {
        "id": "rbi_cross_border_auth_change", "label": "Cross-border card auth change", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Adjusting auth flows for specified cross-border scenarios under Apr 2026 mandate",
        "angle": "Cyber, Financial Services PI",
        "keywords": ["cross-border card", "rbi authentication cross-border", "card auth flow change", "international transaction auth"],
        "priority": 5, "confidence": 68, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "payment_or_card_program": True},
    },
    {
        "id": "dpdp_verifiable_deletion_certificate", "label": "Verifiable deletion certificate adoption", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Sub-processors required to issue cryptographic deletion proof to satisfy DPDP audit",
        "angle": "Cyber, Tech E&O",
        "keywords": ["verifiable deletion", "cryptographic deletion proof", "sub-processor sla", "dpdp deletion certificate"],
        "priority": 5, "confidence": 78,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_dpb_inquiry_received", "label": "DPB Phase I inquiry received", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "DPB-initiated digital inquiries flag heavy Phase II fine exposure",
        "angle": "Cyber, D&O, I-select Liability",
        "keywords": ["dpb inquiry", "data protection board docket", "dpdp phase i investigation", "dpb notice"],
        "priority": 9, "confidence": 92,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_sensitivity": "High", "sdf_probability": 0.8},
    },
    {
        "id": "dpdp_consent_vendor_confirmation", "label": "Consent vendor board confirmation", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "KPMG recommends finalising consent infrastructure ahead of Nov 2026 deadline; absence signals paralysis",
        "angle": "D&O, Business Interruption",
        "keywords": ["consent infrastructure vendor", "consent platform selection", "board minutes consent", "dpdp infra confirmation"],
        "priority": 4, "confidence": 60,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "rbi_nbfc_volume_disclosure", "label": "NBFC third-party volume disclosure", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Enhanced disclosure required by RBI; sudden drops indicate compliance-driven throttling",
        "angle": "D&O, Financial Services PI, Corporate Cover II",
        "keywords": ["nbfc third-party volume", "investor relations transaction volume", "rbi disclosure metric", "partnership volume drop"],
        "priority": 5, "confidence": 65, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
]

# ── Property & Engineering (signals.md lines 138-157) ────────────────────────────
_PROPERTY_ENGINEERING_RULES = [
    {
        "id": "rbi_edge_dc_colocation_bid", "label": "Tier 2/3 edge-DC colocation bid", "regulation": "RBI", "domain": "property_engineering",
        "why": "Rapid local server procurement for 24-hour deletion mandate; under-engineered deployment heightens fire/EEI risk",
        "angle": "Property Fire, Electronic Equipment Insurance, IAR Policy",
        "keywords": ["edge data center", "tier 2 colocation", "tier 3 server bid", "edge dc procurement"],
        "priority": 7, "confidence": 80,
        "profile": {"physical_assets": ["Data centre / server room"], "data_localisation_status": "In-Country"},
    },
    {
        "id": "ondc_gst_radius_mismatch", "label": "ONDC-GSTN radius mismatch", "regulation": "ONDC", "domain": "property_engineering",
        "why": "Seller Apps expanding delivery radii without state-level GST enrollment trigger investigations, liens, BI",
        "angle": "Business Interruption, Bharat Sookshma, MSME Suraksha Kavach",
        "keywords": ["ondc serviceability radius", "gstn state registration", "delivery radius mismatch", "ondc gst boundary"],
        "priority": 8, "confidence": 88,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"], "state_footprint": ["Karnataka"]},
    },
    {
        "id": "dgca_type_cert_rejection", "label": "DGCA Type Certification rejection", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Failed structural or NPNT software tests render manufactured drone inventory unsellable",
        "angle": "Engineering CAR/EAR, Product Liability, Drone RPAS",
        "keywords": ["dgca type certification", "type test rejection", "npnt test failure", "drone certification denied"],
        "priority": 8, "confidence": 90, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment", "Manufacturing plant / factory"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_drone_import_alert", "label": "Assembled-drone customs alert", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Customs seizure of fully assembled drones (CBU/CKD/SKD) disrupts hardware supply chains",
        "angle": "Marine Cargo, Trade Credit, Marine Transit",
        "keywords": ["assembled drone import", "drone customs seizure", "cbu drone import ban", "ckd drone alert"],
        "priority": 7, "confidence": 82, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"], "export_us_pct": 0.0},
    },
    {
        "id": "dgca_lithium_test_facility", "label": "Lithium VTOL test facility expansion", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Scaled physical battery testing for novel VTOL designs introduces thermal runaway and fire risk",
        "angle": "Property Fire, Machinery Breakdown, Industrial All Risk (IAR)",
        "keywords": ["lithium-ion testing", "vtol test facility", "drone battery test", "thermal runaway lab"],
        "priority": 6, "confidence": 75,
        "profile": {"physical_assets": ["Lab / R&D equipment", "Manufacturing plant / factory"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "rapid_hvac_server_install", "label": "Rapid HVAC / rack install (no reinforcement)", "regulation": "", "domain": "property_engineering",
        "why": "Building local data capacity rapidly increases structural, electrical, and fire risks",
        "angle": "Property All Risk, Electronic Equipment, Business Edge Policy",
        "keywords": ["hvac server install", "server rack reinforcement", "rapid datacenter deployment", "rack structural load"],
        "priority": 5, "confidence": 55,
        "profile": {"physical_assets": ["Data centre / server room"]},
    },
    {
        "id": "rbi_lsp_cash_safe_deployment", "label": "LSP regional cash-safe deployment", "regulation": "RBI", "domain": "property_engineering",
        "why": "High-volume physical cash recovery hubs create concentrated burglary targets",
        "angle": "Burglary and Housebreaking, Crime / Fidelity, Money Insurance",
        "keywords": ["cash safe deployment", "lsp regional hub", "vault procurement lending", "physical cash recovery hub"],
        "priority": 6, "confidence": 75, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "dgca_npnt_module_upgrade", "label": "NPNT module manufacturing upgrade", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Mfg-line upgrades for mandated NPNT chips introduce transition and machinery breakdown risk",
        "angle": "Electronic Equipment, Drone RPAS, Engineering CPM",
        "keywords": ["npnt module", "no permission no takeoff chip", "drone hardware nptn", "npnt firmware"],
        "priority": 7, "confidence": 85, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Manufacturing plant / factory", "Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_dark_store_gst_surge", "label": "ONDC dark-store GST registration surge", "regulation": "GST", "domain": "property_engineering",
        "why": "Dark-store networks expanding to match ONDC serviceability increase aggregate property exposure",
        "angle": "Bharat Laghu Udyam Suraksha, Property Fire, Burglary",
        "keywords": ["dark store gst", "gstn new registration", "quick commerce dark store", "ondc fulfilment hub"],
        "priority": 6, "confidence": 75,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre", "Retail stores / kiosks"], "operations": "Hybrid"},
    },
    {
        "id": "dpdp_foreign_server_decommission", "label": "Foreign server rack decommission", "regulation": "DPDP", "domain": "property_engineering",
        "why": "Tearing down foreign infrastructure under cross-border restrictions; risk during hardware transit",
        "angle": "Electronic Equipment, Business Interruption, Marine Cargo",
        "keywords": ["foreign server decommission", "cloud migration teardown", "cross-border infra removal", "data localisation rack"],
        "priority": 6, "confidence": 75,
        "profile": {"regulatory": ["DPDP Act obligations"], "data_localisation_status": "In-Country"},
    },
    {
        "id": "dpdp_verifiable_deletion_appliance", "label": "Verifiable deletion appliance install", "regulation": "DPDP", "domain": "property_engineering",
        "why": "Cryptographic hardware required for DPDP verifiable deletion; failure halts processing",
        "angle": "Electronic Equipment Insurance, IAR Policy",
        "keywords": ["verifiable deletion appliance", "cryptographic deletion hardware", "dpdp hsm", "deletion appliance install"],
        "priority": 5, "confidence": 75,
        "profile": {"physical_assets": ["Data centre / server room"], "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dgca_pli_factory_filing", "label": "PLI scheme factory floor filing", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Scaling drone mfg lines for ₹2000 cr PLI outlay; major EAR/CAR exposure during expansion",
        "angle": "Engineering CAR/EAR, Property All Risk, Corporate Cover II",
        "keywords": ["pli scheme drone", "drone manufacturing pli", "production linked incentive drone", "civil aviation factory filing"],
        "priority": 6, "confidence": 80, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Manufacturing plant / factory"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_drone_component_warehouse_shift", "label": "Drone component warehouse shift", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Shifts in flammable component storage (batteries, motors) increase marine cargo and static fire risk",
        "angle": "Marine Cargo, Property Fire, Bharat Sookshma",
        "keywords": ["drone component warehouse", "drone battery storage", "uav component inventory", "drone motor stockpile"],
        "priority": 5, "confidence": 68,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_bvlos_corridor_request", "label": "BVLOS corridor expansion request", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Beyond Visual Line of Sight test corridors exponentially increase third-party property damage risk",
        "angle": "Public Liability, Drone RPAS, CGL / I-Elite",
        "keywords": ["bvlos corridor", "beyond visual line of sight", "drone test flight expansion", "bvlos airspace"],
        "priority": 7, "confidence": 85, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dpdp_grievance_kiosk_install", "label": "Physical grievance kiosk install", "regulation": "DPDP", "domain": "property_engineering",
        "why": "Physical channels to comply with DPDP accessibility for grievance redressal across demographics",
        "angle": "Property Fire, Burglary, Merchants Cover III",
        "keywords": ["grievance kiosk", "dpdp accessibility channel", "retail grievance booth", "physical grievance redressal"],
        "priority": 4, "confidence": 60,
        "profile": {"physical_assets": ["Retail stores / kiosks"], "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dgca_uin_plate_retrofit", "label": "DGCA UIN plate retrofit", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Mandatory physical retrofitting of legacy drones; handling errors lead to hardware damage",
        "angle": "Drone RPAS, Machinery Breakdown, Engineering EEI",
        "keywords": ["dgca uin retrofit", "drone uin plate", "unique identification number drone", "legacy drone retrofit"],
        "priority": 5, "confidence": 78, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_iot_inventory_sensor", "label": "ONDC IoT inventory sensor deployment", "regulation": "ONDC", "domain": "property_engineering",
        "why": "Sensors for real-time ONDC inventory; failure causes API desync and business interruption",
        "angle": "Electronic Equipment, Business Interruption, Enterprise Secure Package",
        "keywords": ["ondc iot sensor", "warehouse iot inventory", "ondc inventory sync", "real-time inventory sensor"],
        "priority": 5, "confidence": 70,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"], "ai_in_product": True},
    },
    {
        "id": "rbi_floorplan_silo_alteration", "label": "Multi-lender floorplan silo alteration", "regulation": "RBI", "domain": "property_engineering",
        "why": "REs physically siloing competing-LSP operations under RBI impartiality rules modifies building risk profile",
        "angle": "Property All Risk, Business Shield SME",
        "keywords": ["floorplan alteration", "multi-lender silo", "physical separation lsp", "lender operations partition"],
        "priority": 4, "confidence": 60, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "dgca_uncertified_battery_stockpile", "label": "Uncertified drone battery stockpile", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Holding batteries awaiting Type Certification creates unmanaged high-density fire load",
        "angle": "Property Fire, Industrial All Risk (IAR)",
        "keywords": ["uncertified drone battery", "drone battery warehouse", "type certification pending battery", "uav lithium stockpile"],
        "priority": 7, "confidence": 80, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Warehouse / fulfilment centre", "Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_rpto_facility_expansion", "label": "RPTO facility expansion", "regulation": "DGCA", "domain": "property_engineering",
        "why": "Remote Pilot Training Organization facilities scale to meet RPC demand; high public liability footfall",
        "angle": "Public Liability, Property All Risk, Drone RPAS",
        "keywords": ["rpto facility", "remote pilot training organization", "drone pilot training ground", "rpc training expansion"],
        "priority": 5, "confidence": 80, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Lab / R&D equipment"], "regulatory": ["DGCA / drone operations"]},
    },
]

# ── Employee Benefits (signals.md lines 169-191) ─────────────────────────────────
_EMPLOYEE_BENEFITS_RULES = [
    {
        "id": "kgw_upi_autopay_delay", "label": "Welfare Board UPI-autopay delay", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Failure to remit 1-2% GMV cess dynamically; missed remittances trigger state penalties and B2G blacklisting",
        "angle": "Employers Compensation, D&O, MSME Suraksha Kavach",
        "keywords": ["welfare board upi autopay", "gmv cess remittance", "karnataka welfare cess", "upi autopay delay"],
        "priority": 8, "confidence": 90,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.5, "state_footprint": ["Karnataka"]},
    },
    {
        "id": "kgw_gstn_welfare_mismatch", "label": "GSTN-Welfare Board mismatch >5%", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Triggers 200% automated penalty on evaded amounts; indicates severe accounting failure and D&O exposure",
        "angle": "D&O, Business Interruption, Directors and Officers Liability",
        "keywords": ["gstn welfare board", "gstn-welfare board", "5 percent discrepancy", "200 percent penalty cess", "gmv mismatch karnataka", "welfare cess mismatch", "welfare cess audit"],
        "priority": 9, "confidence": 92,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.5},
    },
    {
        "id": "kgw_kyc_failure_spike", "label": "Gig worker 30-day KYC failure", "regulation": "KGW", "domain": "employee_benefits",
        "why": "30-day KYC failures imply transient, unverified workforce — elevates PA and Crime risks",
        "angle": "Group Personal Accident, Crime / Fidelity, Employers Compensation",
        "keywords": ["30-day kyc failure", "gig worker kyc", "aggregator onboarding failure", "karnataka kyc mandate"],
        "priority": 7, "confidence": 78,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.5},
    },
    {
        "id": "kgw_idrc_established", "label": "IDRC established (50+ workers)", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Karnataka Bill mandates IDRC for >50 workers; case volume signals systemic worker unrest",
        "angle": "Employment Practices Liability, Employers Compensation, Business Shield SME",
        "keywords": ["internal dispute resolution committee", "idrc established", "karnataka gig committee", "platform worker idrc"],
        "priority": 6, "confidence": 80,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "kgw_algo_transparency_dashboard", "label": "Algorithmic transparency dashboard", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Mandatory disclosure of fare/rating/task allocation algorithms to workers",
        "angle": "Tech E&O, Employment Practices Liability",
        "keywords": ["algorithmic transparency", "rider app dashboard", "fare algorithm disclosure", "task allocation transparency"],
        "priority": 5, "confidence": 72,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "ai_in_product": True},
    },
    {
        "id": "kgw_labour_tribunal_appeal", "label": "Labour Tribunal platform-ban appeal", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Workers using 90-day adjudication mandate to contest algorithmic bans; high volume signals EPL risk",
        "angle": "Employment Practices Liability, D&O, Corporate Cover II",
        "keywords": ["labour tribunal appeal", "platform ban appeal", "90-day adjudication", "algorithmic ban contest"],
        "priority": 7, "confidence": 82,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_benefit_portability_api", "label": "Cross-state benefit portability API", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Karnataka portability for migrant gig workers; models geographic concentration for group policies",
        "angle": "Group Health, Group PA, Group Safeguard Insurance",
        "keywords": ["benefit portability api", "national gig id", "cross-state gig migration", "karnataka portable benefit"],
        "priority": 5, "confidence": 70,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "kgw_throttling_algo_removal", "label": "Algorithmic throttling removal", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Platforms adjusting safety-impacting algorithms to avoid Welfare Board veto",
        "angle": "Employers Compensation, Public Liability",
        "keywords": ["throttling mechanism removed", "radius reduction reversed", "welfare board veto avoidance", "platform safety algo"],
        "priority": 6, "confidence": 70,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "dpdp_minor_gig_consent", "label": "Minor gig worker parental consent", "regulation": "DPDP", "domain": "employee_benefits",
        "why": "Ensuring no processing of <18 worker data without parental consent under DPDP",
        "angle": "Cyber, Employment Practices Liability, CGL",
        "keywords": ["minor gig worker", "parental consent worker", "underage delivery onboarding", "minor worker dpdp"],
        "priority": 5, "confidence": 75,
        "profile": {"data_handled": ["Minors' / children's data"], "regulatory": ["DPDP Act obligations", "Labour Codes / gig worker regulations"]},
    },
    {
        "id": "dpdp_fairness_auditor_hiring", "label": "Algorithmic fairness auditor hiring", "regulation": "DPDP", "domain": "employee_benefits",
        "why": "Reactive hiring for DPDP SDF obligations and gig transparency laws simultaneously",
        "angle": "Employment Practices Liability, D&O, Cyber",
        "keywords": ["algorithmic fairness auditor", "ai fairness hire", "sdf fairness role", "dpdp auditor recruit"],
        "priority": 5, "confidence": 78,
        "profile": {"ai_in_product": True, "sdf_probability": 0.65, "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "kgw_piece_rate_to_hourly", "label": "Piece-rate to hourly payout shift", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Restructuring to circumvent piece-rate definitions in Gig Worker Act — aggressive regulatory evasion",
        "angle": "D&O, Employment Practices Liability, Crime / Fidelity",
        "keywords": ["piece-rate payout", "hourly compensation shift", "karnataka cess evasion", "payout architecture restructure"],
        "priority": 7, "confidence": 80,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_state_gig_id_collectivization", "label": "State Gig ID collectivization chatter", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Workers leveraging state-issued IDs to organize verified digital strikes — fulfilment delay risk",
        "angle": "Business Interruption, Employers Compensation",
        "keywords": ["state gig id", "digital strike platform", "gig worker collective", "karnataka union chatter"],
        "priority": 6, "confidence": 72,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.5},
    },
    {
        "id": "kgw_b2g_blacklist_notice", "label": "B2G blacklisting notice", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Welfare cess non-remittance retaliation; severs up to 15% of B2G orders — immediate revenue hit",
        "angle": "Business Interruption, D&O, Corporate Cover II",
        "keywords": ["b2g blacklist", "government e-marketplace", "gem blacklisting", "welfare cess retaliation"],
        "priority": 8, "confidence": 85,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_id_act_appeal", "label": "Industrial Disputes Act appeal", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Karnataka Bill bridges gig work to formal employment liability via ID Act 1947",
        "angle": "Employers Compensation, Employment Practices Liability",
        "keywords": ["industrial disputes act", "id act 1947 appeal", "gig worker formal employment", "karnataka id act gig"],
        "priority": 6, "confidence": 80,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_shops_act_license_suspension", "label": "Shops Act license suspension", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Triggered by non-compliance with gig worker registration and cess mandates",
        "angle": "Business Interruption, D&O, Business Shield SME",
        "keywords": ["shops and establishments act", "license suspension karnataka", "municipal gazette suspension", "gig non-compliance license"],
        "priority": 6, "confidence": 78,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_gamified_incentive_rollback", "label": "Gamified incentive rollback", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Removing behavioral monitoring tools deemed unfair/unsafe by Welfare Board",
        "angle": "Tech E&O, Employment Practices Liability, Employers Compensation",
        "keywords": ["gamified incentive removed", "behavioral monitoring tool", "high-risk incentive rollback", "gig gamification"],
        "priority": 5, "confidence": 65,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_conciliation_hire_localised", "label": "Localised conciliation officer hire", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Internal scaling for pre-tribunal dispute resolution; high hiring volume = high dispute volume",
        "angle": "Employment Practices Liability",
        "keywords": ["conciliation officer hire", "pre-tribunal officer", "local dispute conciliator", "karnataka conciliation"],
        "priority": 5, "confidence": 75,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_group_health_api_surge", "label": "Group Health/PA insurtech query surge", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Platforms seeking secondary coverage to supplement state-board benefits in competitive labor market",
        "angle": "Group Health, Group PA, Group Safeguard Insurance",
        "keywords": ["group health api surge", "gig insurtech query", "secondary coverage platform", "fleet group pa"],
        "priority": 4, "confidence": 55,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "dpdp_gig_data_silo_policy", "label": "Gig worker data silo policy update", "regulation": "DPDP", "domain": "employee_benefits",
        "why": "Ensuring gig worker data not repurposed without itemized consent",
        "angle": "Cyber, Employment Practices Liability",
        "keywords": ["gig worker data silo", "worker data repurpose", "itemized consent worker", "dpo gig policy"],
        "priority": 5, "confidence": 65,
        "profile": {"regulatory": ["DPDP Act obligations"], "gig_headcount_pct": 0.4},
    },
    {
        "id": "kgw_safety_training_module", "label": "Mandatory safety training module", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Addressing Karnataka OHS mandates; training failure correlates with systemic EC risk",
        "angle": "Employers Compensation, Group PA",
        "keywords": ["safety training module", "occupational health safety gig", "driver app training", "karnataka ohs"],
        "priority": 5, "confidence": 70,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "kgw_tier3_withdrawal", "label": "Tier-3 Karnataka withdrawal", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Platforms retreating from low-margin geographies where 1-2% GMV cess renders unit economics negative",
        "angle": "Business Interruption, D&O",
        "keywords": ["tier-3 karnataka withdrawal", "service availability map", "platform retreat karnataka", "gig cess retreat"],
        "priority": 5, "confidence": 65,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"], "state_footprint": ["Karnataka"]},
    },
    {
        "id": "dpdp_key_person_insurance_surge", "label": "Key Person insurance procurement surge", "regulation": "DPDP", "domain": "employee_benefits",
        "why": "DPOs and CCOs covered for direct personal liability under DPDP and RBI rules",
        "angle": "Key Person, D&O, Business Shield SME",
        "keywords": ["key person insurance", "dpo coverage purchase", "chief compliance officer insurance", "ccob personal liability"],
        "priority": 5, "confidence": 70,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpdp_employee_data_grievance", "label": "Employee data-access grievance", "regulation": "DPDP", "domain": "employee_benefits",
        "why": "Employees using DPDP Data Principal rights for HR data access; poor handling triggers DPB complaints",
        "angle": "Employment Practices Liability, Cyber",
        "keywords": ["employee data access grievance", "hr data principal request", "dpdp employee rights", "it helpdesk data grievance"],
        "priority": 4, "confidence": 60,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
]

# ── Transit / Motor / Trade (signals.md lines 202-223) ───────────────────────────
_TRANSIT_MOTOR_RULES = [
    {
        "id": "dgca_npnt_log_failure", "label": "NPNT log failure spike", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Drone fleets bypassing firmware locks or flying restricted zones; high regulatory grounding probability",
        "angle": "Drone RPAS, Public Liability, Commercial Motor Fleet",
        "keywords": ["npnt log failure", "no permission no takeoff failure", "drone firmware bypass", "restricted zone flight"],
        "priority": 9, "confidence": 90, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_uin_revocation", "label": "DGCA UIN revocation", "regulation": "DGCA", "domain": "transit_motor",
        "why": "DGCA deregistering drones grounds assets and destroys transit capacity",
        "angle": "Drone RPAS, Business Interruption, Marine Transit",
        "keywords": ["uin revocation", "egca portal notice", "dgca deregister drone", "unique identification number revoked"],
        "priority": 8, "confidence": 90, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_edge_logistics_investigation", "label": "ONDC edge-case logistics investigation", "regulation": "ONDC", "domain": "transit_motor",
        "why": "ONDC intervening in lost/damaged cargo disputes indicates transit chain breakdown",
        "angle": "Marine Cargo, Trade Credit, Professional Indemnity",
        "keywords": ["ondc logistics investigation", "lost cargo dispute ondc", "lsp damaged cargo", "ondc transit edge case"],
        "priority": 7, "confidence": 82,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"]},
    },
    {
        "id": "dgca_rpc_expiry", "label": "RPC expiration across fleet", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Expired Remote Pilot Certificates invalidate aviation insurance",
        "angle": "Drone RPAS, Employers Compensation, Public Liability",
        "keywords": ["remote pilot certificate", "rpc expiry", "drone pilot license expired", "digital sky rpc registry"],
        "priority": 7, "confidence": 85, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_micro_to_small_upgrade", "label": "Micro→Small drone UIN upgrade", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Small category drones face stricter compliance and higher kinetic energy risks",
        "angle": "Drone RPAS, Public Liability, CGL / I-Elite",
        "keywords": ["micro to small drone", "drone category upgrade", "uin registration small", "drone fleet upsize"],
        "priority": 6, "confidence": 75, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_mobility_trip_volatility", "label": "ONDC Mobility trip volume volatility", "regulation": "ONDC", "domain": "transit_motor",
        "why": "Volatility in 1L daily trips stresses routing algorithms, fleet maintenance, driver fatigue",
        "angle": "Commercial Motor Fleet, Transit, Public Liability",
        "keywords": ["ondc mobility network", "1 lakh daily trips", "ondc trip volatility", "ondc ride volume"],
        "priority": 6, "confidence": 75,
        "profile": {"physical_assets": ["Vehicles / delivery fleet"], "fleet_count": 100},
    },
    {
        "id": "dgca_egca_migration_failure", "label": "Digital Sky→eGCA migration failure", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Failure to migrate to eGCA single-window for D-1 to D-5 forms causes administrative paralysis",
        "angle": "Business Interruption, Tech E&O, Drone RPAS",
        "keywords": ["egca portal migration", "digital sky login failure", "d-1 to d-5 forms", "egca single window"],
        "priority": 6, "confidence": 80, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_serviceability_bounce", "label": "ONDC serviceability API bounce", "regulation": "ONDC", "domain": "transit_motor",
        "why": "Failure to fulfil orders outside registered GST boundaries causes mass cancellations",
        "angle": "Marine Cargo, Trade Credit, Merchants Cover III",
        "keywords": ["serviceability api bounce", "ondc fulfilment fail", "gst boundary cancellation", "ondc api response code"],
        "priority": 6, "confidence": 78,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"]},
    },
    {
        "id": "dgca_green_zone_compliance", "label": "Green Zone strict compliance", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Fleets restricting to 400ft AGL VLOS — positive signal lowering transit/liability risk",
        "angle": "Drone RPAS, Marine Cargo, Enterprise Secure Package",
        "keywords": ["green zone compliance", "400ft agl", "vlos restriction", "drone flight planning compliance"],
        "priority": 3, "confidence": 70, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_self_cert_rejection", "label": "Drone self-certification rejection", "regulation": "DGCA", "domain": "transit_motor",
        "why": "DGCA demanding type test data for novel designs previously self-certified",
        "angle": "Machinery Breakdown, Business Interruption, Product Liability",
        "keywords": ["self-certification rejected", "drone type test data", "novel design certification", "vtol type certification"],
        "priority": 6, "confidence": 78, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "ondc_b2b_cancellation_surge", "label": "ONDC B2B cancellation surge", "regulation": "ONDC", "domain": "transit_motor",
        "why": "Systemic wholesale logistics delivery failure massively elevates trade credit exposure",
        "angle": "Trade Credit, Surety, Marine Cargo",
        "keywords": ["ondc b2b cancellation", "wholesale logistics failure", "ondc network cancellation", "b2b transaction abort"],
        "priority": 7, "confidence": 80,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"], "b2b_pct": 0.8},
    },
    {
        "id": "rbi_cash_recovery_routing", "label": "Cash-recovery algorithmic routing", "regulation": "RBI", "domain": "transit_motor",
        "why": "Optimized routes for same-day cash deposits increase targeted hijacking and transit risks",
        "angle": "Money Insurance, Crime / Fidelity, Transit",
        "keywords": ["cash recovery routing", "lsp logistics route", "physical cash recovery transit", "algorithmic cash route"],
        "priority": 6, "confidence": 72, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "rto_commercial_ev_bulk", "label": "Commercial EV bulk RTO registration", "regulation": "", "domain": "transit_motor",
        "why": "Gig platform shifting from third-party fleet to captive EVs shifts risk to corporate balance sheet",
        "angle": "Commercial Motor Fleet, Marine Transit, IAR Policy",
        "keywords": ["commercial ev rto", "vahan registration bulk", "captive electric fleet", "ev fleet registration"],
        "priority": 6, "confidence": 75,
        "profile": {"physical_assets": ["Vehicles / delivery fleet"], "vehicle_types": ["Electric two-wheeler", "Electric three-wheeler"], "fleet_count": 200},
    },
    {
        "id": "freight_algo_matching_drop", "label": "Freight algo matching drop", "regulation": "", "domain": "transit_motor",
        "why": "Match efficiency drop indicates network inefficiency, transit delays, and spoilage for temp-sensitive cargo",
        "angle": "Marine Cargo, Business Interruption, Trade Credit",
        "keywords": ["freight algorithmic matching", "load matching efficiency", "freight aggregator api drop", "freight corridor failure"],
        "priority": 5, "confidence": 60,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"], "ai_in_product": True},
    },
    {
        "id": "dpdp_dashcam_blur", "label": "DPDP dashcam facial blurring", "regulation": "DPDP", "domain": "transit_motor",
        "why": "Fleets masking civilian faces to avoid DPDP unauthorized behavioral monitoring fines",
        "angle": "Cyber, Tech E&O, Commercial Motor Fleet",
        "keywords": ["dashcam facial blur", "dpdp dashcam", "fleet camera privacy", "behavioral monitoring fleet"],
        "priority": 4, "confidence": 70,
        "profile": {"physical_assets": ["Vehicles / delivery fleet"], "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "dpb_transit_complaint", "label": "Transit-related DPB complaint", "regulation": "DPDP", "domain": "transit_motor",
        "why": "Consumer complaints about excessive post-delivery location tracking",
        "angle": "Cyber, Tech E&O, D&O",
        "keywords": ["dpb transit complaint", "post-delivery tracking complaint", "logistics location tracking", "delivery app gps complaint"],
        "priority": 5, "confidence": 75,
        "profile": {"data_handled": ["Location / GPS tracking data"], "regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "ondc_eway_bill_automation", "label": "ONDC e-Way bill GST automation", "regulation": "GST", "domain": "transit_motor",
        "why": "Positive signal — automation of compliance between ONDC orders and transit tax",
        "angle": "Surety, Trade Credit, Corporate Cover II",
        "keywords": ["e-way bill automation", "ondc gst sync", "supply chain erp gst", "transit tax automation"],
        "priority": 3, "confidence": 65,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"]},
    },
    {
        "id": "dgca_altimeter_spoof", "label": "Drone altimeter spoofing report", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Illegal hardware spoofing to bypass 120m AGL Green Zone — extreme aviation/cyber/liability risk",
        "angle": "Drone RPAS, Public Liability, Crime / Fidelity",
        "keywords": ["altimeter spoofing", "drone hardware manipulation", "agl bypass drone", "120m altitude bypass"],
        "priority": 8, "confidence": 85, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "dgca_drone_component_customs_delay", "label": "Drone component customs delay", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Customs scrutiny of SKD kits delays domestic drone assembly",
        "angle": "Marine Cargo, Business Interruption, Trade Credit",
        "keywords": ["drone component customs", "skd kit customs", "drone import delay", "uav port clearance"],
        "priority": 6, "confidence": 75, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"], "physical_assets": ["Warehouse / fulfilment centre"]},
    },
    {
        "id": "rbi_lsp_captive_logistics_partner", "label": "LSP-captive logistics partnership", "regulation": "RBI", "domain": "transit_motor",
        "why": "Digital lenders securing physical asset recovery — high-risk financial-physical interface",
        "angle": "Corporate Cover II, Enterprise Secure Package",
        "keywords": ["lsp captive logistics", "asset recovery partnership", "digital lender repo network", "physical recovery partner"],
        "priority": 6, "confidence": 70, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"], "physical_assets": ["Vehicles / delivery fleet"]},
    },
    {
        "id": "dgca_rule13_aerodrome", "label": "Rule 13 aerodrome photo permission", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Flying near sensitive infrastructure — high-value contracts, catastrophic third-party risk",
        "angle": "Drone RPAS, CGL / I-Elite, Public Liability",
        "keywords": ["rule 13 aerodrome", "aerodrome photography permission", "drone sensitive infrastructure", "dgca permission log"],
        "priority": 7, "confidence": 85, "sector": "Deeptech / AI / Robotics",
        "profile": {"physical_assets": ["Drones / UAV equipment"], "regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "marine_transit_config_change", "label": "Cross-border marine transit reconfig", "regulation": "", "domain": "transit_motor",
        "why": "Adjusting transit coverage for data-localisation supply chain realignments",
        "angle": "Marine Cargo, Trade Credit, MSME Suraksha Kavach",
        "keywords": ["marine transit reconfiguration", "cross-border insurtech update", "supply chain realignment insurance", "data localisation transit"],
        "priority": 4, "confidence": 55,
        "profile": {"physical_assets": ["Warehouse / fulfilment centre"]},
    },
]


# ── Catchall regulation rules (fire on broad regulatory phrases at LOW confidence;
#    surface regulation badge so RM can investigate even when specific rule misses) ─
_CATCHALL_RULES = [
    {
        "id": "dpdp_general", "label": "DPDP Act mention", "regulation": "DPDP", "domain": "cyber_financial",
        "why": "Article references DPDP Act — verify which DPDP obligation applies (SDF / breach / consent / minors / DPO)",
        "angle": "Cyber, D&O",
        "keywords": ["dpdp", "data protection rules", "data protection board", "personal data protection"],
        "priority": 1, "confidence": 50,
        "profile": {"regulatory": ["DPDP Act obligations"]},
    },
    {
        "id": "rbi_general", "label": "RBI regulation mention", "regulation": "RBI", "domain": "cyber_financial",
        "why": "Article references RBI compliance — verify whether digital lending, payment auth, or NBFC rules apply",
        "angle": "Cyber, Financial Services PI, D&O",
        "keywords": ["rbi guideline", "rbi norm", "rbi rule", "rbi compliance", "reserve bank of india"],
        "priority": 1, "confidence": 48, "sector": "Fintech",
        "profile": {"regulatory": ["RBI / SEBI / IRDAI licensed"]},
    },
    {
        "id": "ondc_general", "label": "ONDC network mention", "regulation": "ONDC", "domain": "liability",
        "why": "Article references ONDC — verify whether seller, buyer, logistics, or grievance role triggers liability",
        "angle": "Tech E&O, Public Liability, Product Liability",
        "keywords": ["ondc", "open network for digital commerce", "ondc seller", "ondc buyer app"],
        "priority": 1, "confidence": 48,
        "profile": {"data_sensitivity": "High"},
    },
    {
        "id": "dgca_general", "label": "DGCA drone mention", "regulation": "DGCA", "domain": "transit_motor",
        "why": "Article references DGCA / drone rules — verify which DGCA rule (UIN, type cert, NPNT, BVLOS) is invoked",
        "angle": "Drone RPAS, Public Liability",
        "keywords": ["dgca", "drone rules", "digital sky", "egca portal", "uav regulation"],
        "priority": 1, "confidence": 50, "sector": "Deeptech / AI / Robotics",
        "profile": {"regulatory": ["DGCA / drone operations"]},
    },
    {
        "id": "kgw_general", "label": "Karnataka gig worker mention", "regulation": "KGW", "domain": "employee_benefits",
        "why": "Article references Karnataka platform gig worker law — verify cess, IDRC, KYC or tribunal trigger",
        "angle": "Employment Practices Liability, Employers Compensation",
        "keywords": ["gig worker bill", "platform-based gig", "karnataka gig", "gig worker welfare", "platform worker act"],
        "priority": 1, "confidence": 50,
        "profile": {"regulatory": ["Labour Codes / gig worker regulations"]},
    },
    {
        "id": "gst_general", "label": "GST compliance mention", "regulation": "GST", "domain": "property_engineering",
        "why": "Article references GST event affecting digital operations — verify whether ONDC serviceability or dark-store linkage applies",
        "angle": "Business Interruption, MSME Suraksha Kavach",
        "keywords": ["gst notice", "gstn audit", "gst registration", "gst council"],
        "priority": 1, "confidence": 45,
        "profile": {},
    },
]


SIGNAL_RULES = [
    *_LEGACY_RULES,
    *_LIABILITY_RULES,
    *_CYBER_FINANCIAL_RULES,
    *_PROPERTY_ENGINEERING_RULES,
    *_EMPLOYEE_BENEFITS_RULES,
    *_TRANSIT_MOTOR_RULES,
    *_CATCHALL_RULES,
]

# Guard against accidental duplicate IDs when expanding the catalog
_ids = [r["id"] for r in SIGNAL_RULES]
assert len(_ids) == len(set(_ids)), f"Duplicate signal rule IDs: {[i for i in _ids if _ids.count(i) > 1]}"
