GLOBAL_PRODUCT_CATALOG = {
    "ai_performance_warranty": {
        "name": "AI Performance Warranty / Model Liability Insurance",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "Expected 2026-27 via IRDAI Sandbox or Lloyd's India placement.",
        "providers": "Munich Re aiSure / Armilla AI Warranty / Vouch AI Insurance",
        "india_status": "Lloyd's-placeable today; sandbox filing expected",
        "what_it_covers": "Parametric model underperformance, hallucination, drift, bias, AI regulatory investigation, and model-training IP claims.",
        "icici_equivalent": "Cyber Liability + Professional Indemnity (Tech) - partial coverage only",
        "icici_gap": "Standard cyber and PI policies usually do not affirmatively cover AI model performance triggers.",
        "best_for": "AI-native SaaS, deeptech, health AI, fintech underwriting.",
        "risk_map": {"IP Infringement Risk": 0.9, "Liability Risk": 0.8, "Policy Velocity Risk": 0.7},
        "sector_relevance": {"Deeptech / AI / Robotics", "SaaS / Enterprise Software", "Healthtech", "Fintech"},
        "size_buckets": {"micro": {"min_lakh": 1.0, "max_lakh": 4.0}, "small": {"min_lakh": 4.0, "max_lakh": 15.0}, "growth": {"min_lakh": 15.0, "max_lakh": 50.0}},
    },
    "parametric_weather_climate": {
        "name": "Parametric Weather / Climate Cover",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "Expected through climate-risk sandbox filings.",
        "providers": "Kita / Oka / Lloyd's parametric markets",
        "india_status": "Global-only for most startup use cases",
        "what_it_covers": "Rainfall, heat, flood, drought, and climate index triggers without conventional loss adjustment.",
        "icici_equivalent": "Property Fire / Property All Risk - indemnity basis",
        "icici_gap": "No startup-specific climate index payout for revenue interruption.",
        "best_for": "Agritech, cleantech, logistics, D2C physical inventory.",
        "risk_map": {"ESG & Climate Risk": 1.0, "Property Risk": 0.7},
        "sector_relevance": {"Agritech", "Cleantech / Climatetech", "Logistics / Mobility", "D2C / Consumer Brands"},
        "size_buckets": {"micro": {"min_lakh": 0.5, "max_lakh": 2.0}, "small": {"min_lakh": 2.0, "max_lakh": 8.0}, "growth": {"min_lakh": 8.0, "max_lakh": 25.0}},
    },
    "cbam_carbon_levy_parametric": {
        "name": "CBAM Carbon Levy Parametric Cover",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "Potential 2026-27 product development route for EU-exporting Indian firms.",
        "providers": "Kita / Oka / specialty Lloyd's markets",
        "india_status": "Not yet filed in India",
        "what_it_covers": "Carbon levy volatility when EU carbon prices or CBAM liabilities exceed contracted thresholds.",
        "icici_equivalent": "No direct equivalent",
        "icici_gap": "No affirmative CBAM levy volatility product.",
        "best_for": "EU-exporting cleantech, agritech, D2C, logistics, and manufacturing-linked startups.",
        "risk_map": {"ESG & Climate Risk": 0.9, "Geopolitical Risk": 0.8},
        "sector_relevance": {"Cleantech / Climatetech", "D2C / Consumer Brands", "Agritech", "Logistics / Mobility"},
        "size_buckets": {"micro": {"min_lakh": 0.8, "max_lakh": 3.0}, "small": {"min_lakh": 3.0, "max_lakh": 10.0}, "growth": {"min_lakh": 10.0, "max_lakh": 35.0}},
    },
    "quantum_cryptographic_liability": {
        "name": "Quantum Cryptographic Liability",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "Longer-horizon specialty liability opportunity.",
        "providers": "IBM Quantum Risk Advisory / Munich Re emerging tech markets",
        "india_status": "Not available as admitted Indian product",
        "what_it_covers": "Liability from cryptographic obsolescence and retrospective decryption of sensitive data.",
        "icici_equivalent": "Cyber Liability - partial breach response only",
        "icici_gap": "No affirmative harvest-now-decrypt-later liability trigger.",
        "best_for": "Fintech, healthtech, deeptech, and security SaaS.",
        "risk_map": {"Cyber Technical Risk": 0.9, "IP Infringement Risk": 0.6, "Data Privacy Risk": 0.7},
        "sector_relevance": {"Fintech", "Healthtech", "Deeptech / AI / Robotics", "SaaS / Enterprise Software"},
        "size_buckets": {"micro": {"min_lakh": 1.0, "max_lakh": 4.0}, "small": {"min_lakh": 4.0, "max_lakh": 12.0}, "growth": {"min_lakh": 12.0, "max_lakh": 40.0}},
    },
    "wage_protection_gig": {
        "name": "Gig Platform Wage Protection",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "Likely via micro-insurance or platform-worker sandbox products.",
        "providers": "Uber x AXA / Deliveroo x Zurich / Stride Health",
        "india_status": "No direct Indian equivalent",
        "what_it_covers": "Income protection for platform workers unable to work due to illness, accident, or covered suspension.",
        "icici_equivalent": "Group PA + Employee Health - partial coverage only",
        "icici_gap": "No direct platform wage-replacement obligation cover.",
        "best_for": "Logistics, foodtech, HRtech, and gig-enabled agritech.",
        "risk_map": {"Gig & Labour Risk": 1.0, "Regulatory Compliance Risk": 0.7},
        "sector_relevance": {"Logistics / Mobility", "Foodtech / Cloud Kitchen", "HRtech", "Agritech"},
        "size_buckets": {"micro": {"min_lakh": 0.5, "max_lakh": 2.0}, "small": {"min_lakh": 2.0, "max_lakh": 9.0}, "growth": {"min_lakh": 9.0, "max_lakh": 30.0}},
    },
    "reps_warranties_wi": {
        "name": "Representations & Warranties / Warranty & Indemnity",
        "offered_by_icici": False,
        "offered_in_india": False,
        "indian_market_entry_outlook": "M&A broker-led product, not retail startup distribution.",
        "providers": "Aon / Howden / Marsh specialty M&A markets",
        "india_status": "Occasionally placeable for large M&A, not startup retail",
        "what_it_covers": "Losses from breaches of seller representations in acquisitions or strategic investments.",
        "icici_equivalent": "D&O - partial management liability only",
        "icici_gap": "No startup M&A warranty transfer product.",
        "best_for": "Late-stage SaaS, fintech, healthtech, and D2C acquisition targets.",
        "risk_map": {"Governance & Fraud Risk": 0.8, "Liability Risk": 0.5},
        "sector_relevance": {"SaaS / Enterprise Software", "Fintech", "Healthtech", "D2C / Consumer Brands"},
        "size_buckets": {"micro": {"min_lakh": 2.0, "max_lakh": 6.0}, "small": {"min_lakh": 6.0, "max_lakh": 20.0}, "growth": {"min_lakh": 20.0, "max_lakh": 75.0}},
    },
    "active_cyber_response": {
        "name": "Active Cyber Response Insurance",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Available through global cyber specialists and brokers.",
        "providers": "Coalition / Beazley / Chubb",
        "india_status": "Indian-market competitor placement",
        "what_it_covers": "Cyber insurance with active monitoring, takedown support, incident response, and claims services.",
        "icici_equivalent": "Commercial Cyber Liability",
        "icici_gap": "Active risk scanning and MDR-style service bundle is the gap.",
        "best_for": "SaaS, fintech, healthtech, HRtech, legaltech.",
        "risk_map": {"Cyber Technical Risk": 1.0, "Data Privacy Risk": 0.7},
        "sector_relevance": {"SaaS / Enterprise Software", "Fintech", "Healthtech", "HRtech", "Legaltech", "Gaming / Media / Content"},
        "size_buckets": {"micro": {"min_lakh": 0.8, "max_lakh": 3.0}, "small": {"min_lakh": 3.0, "max_lakh": 12.0}, "growth": {"min_lakh": 12.0, "max_lakh": 45.0}},
    },
    "ai_performance_liability": {
        "name": "AI Performance Liability",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Broker-placeable in India through specialty markets.",
        "providers": "Vouch / Armilla / Lloyd's specialty",
        "india_status": "Specialty placement",
        "what_it_covers": "Third-party liability from AI recommendations, model drift, or performance warranties.",
        "icici_equivalent": "PI (Technology)",
        "icici_gap": "AI-specific affirmative wording and model-performance triggers.",
        "best_for": "AI SaaS, health diagnostics, fintech underwriting.",
        "risk_map": {"Liability Risk": 0.8, "IP Infringement Risk": 0.7, "Policy Velocity Risk": 0.6},
        "sector_relevance": {"Deeptech / AI / Robotics", "SaaS / Enterprise Software", "Healthtech", "Fintech", "Legaltech", "HRtech"},
        "size_buckets": {"micro": {"min_lakh": 1.0, "max_lakh": 3.5}, "small": {"min_lakh": 3.5, "max_lakh": 14.0}, "growth": {"min_lakh": 14.0, "max_lakh": 45.0}},
    },
    "supply_chain_cyber": {
        "name": "Supply Chain Cyber Risk",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Relevant for SaaS vendors and manufacturing-linked startups.",
        "providers": "Munich Re SCCR / Beazley",
        "india_status": "Specialty competitor placement",
        "what_it_covers": "Cyber loss caused by critical suppliers, vendors, MSPs, and cloud providers.",
        "icici_equivalent": "Cyber Liability - partial dependent business interruption",
        "icici_gap": "Affirmative third-party supply-chain cyber wording.",
        "best_for": "SaaS, D2C, logistics, deeptech.",
        "risk_map": {"Cyber Technical Risk": 0.8, "Business Interruption Risk": 0.5, "Geopolitical Risk": 0.5},
        "sector_relevance": {"SaaS / Enterprise Software", "D2C / Consumer Brands", "Logistics / Mobility", "Deeptech / AI / Robotics", "Fintech"},
        "size_buckets": {"micro": {"min_lakh": 0.8, "max_lakh": 2.5}, "small": {"min_lakh": 2.5, "max_lakh": 9.0}, "growth": {"min_lakh": 9.0, "max_lakh": 30.0}},
    },
    "iot_device_liability": {
        "name": "IoT Device Liability",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Broker-placeable for connected hardware manufacturers.",
        "providers": "AIG / Beazley / Chubb",
        "india_status": "Specialty placement",
        "what_it_covers": "Connected-device bodily injury, product failure, firmware cyber incidents, and recall expense.",
        "icici_equivalent": "Product Liability + Cyber - partial split coverage",
        "icici_gap": "Integrated IoT failure and cyber-physical liability wording.",
        "best_for": "Deeptech, D2C hardware, healthtech devices, cleantech IoT.",
        "risk_map": {"Liability Risk": 0.9, "Cyber Technical Risk": 0.6, "Property Risk": 0.5},
        "sector_relevance": {"Deeptech / AI / Robotics", "D2C / Consumer Brands", "Healthtech", "Cleantech / Climatetech", "Agritech"},
        "size_buckets": {"micro": {"min_lakh": 0.7, "max_lakh": 3.0}, "small": {"min_lakh": 3.0, "max_lakh": 12.0}, "growth": {"min_lakh": 12.0, "max_lakh": 40.0}},
    },
    "parametric_weather_tata_aig": {
        "name": "Parametric Weather Cover - Indian Sandbox",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Indian sandbox precedent exists.",
        "providers": "Tata AIG / parametric partners",
        "india_status": "Indian competitor sandbox route",
        "what_it_covers": "Weather-triggered payouts for rainfall, heat, and climate volatility.",
        "icici_equivalent": "Property Fire / PAR - indemnity basis",
        "icici_gap": "Trigger-based climate payout product for startups.",
        "best_for": "Agritech, foodtech, logistics, cleantech.",
        "risk_map": {"ESG & Climate Risk": 1.0, "Property Risk": 0.6},
        "sector_relevance": {"Agritech", "Foodtech / Cloud Kitchen", "Logistics / Mobility", "Cleantech / Climatetech"},
        "size_buckets": {"micro": {"min_lakh": 0.3, "max_lakh": 1.5}, "small": {"min_lakh": 1.5, "max_lakh": 6.0}, "growth": {"min_lakh": 6.0, "max_lakh": 20.0}},
    },
    "embedded_eando_sprinto": {
        "name": "Embedded E&O for Compliance Platforms",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Likely through compliance SaaS partnerships.",
        "providers": "Vouch / Vanta / Sprinto model",
        "india_status": "Partner-led model emerging",
        "what_it_covers": "Embedded professional indemnity/E&O inside compliance or certification workflows.",
        "icici_equivalent": "Professional Indemnity",
        "icici_gap": "Embedded distribution and API-first issuance.",
        "best_for": "SaaS, legaltech, HRtech, fintech.",
        "risk_map": {"Liability Risk": 0.8, "Regulatory Compliance Risk": 0.5},
        "sector_relevance": {"SaaS / Enterprise Software", "Legaltech", "HRtech", "Fintech"},
        "size_buckets": {"micro": {"min_lakh": 0.4, "max_lakh": 1.5}, "small": {"min_lakh": 1.5, "max_lakh": 5.0}, "growth": {"min_lakh": 5.0, "max_lakh": 18.0}},
    },
    "trade_credit_ecgc": {
        "name": "ECGC-backed Trade Credit",
        "offered_by_icici": False,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Already established in Indian export credit ecosystem.",
        "providers": "ECGC / trade credit brokers",
        "india_status": "Available in India outside ICICI Lombard retail flow",
        "what_it_covers": "Buyer default, export receivables, and political risk for trade credit.",
        "icici_equivalent": "Trade Credit - partial",
        "icici_gap": "ECGC-backed export-credit integration.",
        "best_for": "Exporting SaaS, D2C, agritech, logistics, and cleantech.",
        "risk_map": {"Governance & Fraud Risk": 0.4, "Geopolitical Risk": 0.7},
        "sector_relevance": {"SaaS / Enterprise Software", "D2C / Consumer Brands", "Agritech", "Logistics / Mobility", "Cleantech / Climatetech", "Fintech"},
        "size_buckets": {"micro": {"min_lakh": 0.4, "max_lakh": 1.5}, "small": {"min_lakh": 1.5, "max_lakh": 5.0}, "growth": {"min_lakh": 5.0, "max_lakh": 18.0}},
    },
    "cyber_il": {
        "name": "ICICI Commercial Cyber Liability",
        "offered_by_icici": True,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Available now.",
        "providers": "ICICI Lombard",
        "india_status": "Available now",
        "what_it_covers": "Data breach, privacy liability, cyber extortion, business interruption, and incident response.",
        "icici_equivalent": "Commercial Cyber Liability",
        "icici_gap": "None for standard cyber liability.",
        "best_for": "Digital startups handling customer or sensitive data.",
        "risk_map": {"Cyber Technical Risk": 1.0, "Data Privacy Risk": 0.8},
        "sector_relevance": {"SaaS / Enterprise Software", "Fintech", "Healthtech", "Edtech", "HRtech", "Legaltech", "Gaming / Media / Content", "D2C / Consumer Brands"},
        "size_buckets": {"micro": {"min_lakh": 0.5, "max_lakh": 2.5}, "small": {"min_lakh": 2.5, "max_lakh": 9.0}, "growth": {"min_lakh": 9.0, "max_lakh": 30.0}},
    },
    "dno_il": {
        "name": "ICICI Directors and Officers Liability",
        "offered_by_icici": True,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Available now.",
        "providers": "ICICI Lombard",
        "india_status": "Available now",
        "what_it_covers": "Management liability, defence costs, investor disputes, and director/officer wrongful acts.",
        "icici_equivalent": "Directors and Officers Liability",
        "icici_gap": "None for standard D&O.",
        "best_for": "Funded startups and board-led companies.",
        "risk_map": {"Governance & Fraud Risk": 0.8, "Reputation Risk": 0.5},
        "sector_relevance": {"SaaS / Enterprise Software", "Fintech", "Healthtech", "Deeptech / AI / Robotics", "D2C / Consumer Brands", "Legaltech", "HRtech"},
        "size_buckets": {"micro": {"min_lakh": 0.8, "max_lakh": 2.0}, "small": {"min_lakh": 2.0, "max_lakh": 6.0}, "growth": {"min_lakh": 6.0, "max_lakh": 20.0}},
    },
    "pi_il": {
        "name": "ICICI Professional Indemnity (Technology)",
        "offered_by_icici": True,
        "offered_in_india": True,
        "indian_market_entry_outlook": "Available now.",
        "providers": "ICICI Lombard",
        "india_status": "Available now",
        "what_it_covers": "Errors, omissions, negligence, contract breach defence, and technology service failure.",
        "icici_equivalent": "Professional Indemnity",
        "icici_gap": "None for standard PI/E&O.",
        "best_for": "SaaS, fintech, legaltech, HRtech, healthtech, and B2B service startups.",
        "risk_map": {"Liability Risk": 0.9, "IP Infringement Risk": 0.4},
        "sector_relevance": {"SaaS / Enterprise Software", "Fintech", "Healthtech", "Legaltech", "HRtech", "Deeptech / AI / Robotics", "Edtech"},
        "size_buckets": {"micro": {"min_lakh": 0.3, "max_lakh": 1.5}, "small": {"min_lakh": 1.5, "max_lakh": 5.0}, "growth": {"min_lakh": 5.0, "max_lakh": 18.0}},
    },
}


def _label(product: dict) -> str:
    if product["offered_by_icici"]:
        return "icici"
    if product["offered_in_india"]:
        return "india_competitor"
    return "not_in_india"


def get_top5_global(scores: dict, sector: str, size_bucket: str, top_n: int = 5) -> list[dict]:
    ranked = []
    for key, product in GLOBAL_PRODUCT_CATALOG.items():
        if sector not in product["sector_relevance"]:
            continue
        weights = product.get("risk_map", {})
        denom = sum(weights.values()) or 1
        relevance = sum(scores.get(cat, 0) * weight for cat, weight in weights.items()) / denom
        premium = product.get("size_buckets", {}).get(size_bucket)
        ranked.append({
            "key": key,
            **product,
            "relevance_score": round(relevance, 1),
            "premium_range": premium,
            "label": _label(product),
        })
    return sorted(ranked, key=lambda item: item["relevance_score"], reverse=True)[:top_n]
